#pragma once
#include "NativeGameplayTags.h"
#include "DarkGameplayTags.generated.h"

UENUM(BlueprintType)
enum class EGameplayTagResistances : uint8
{
	Armor,
	Ice,
	Fire,
	Lightning,
	Holy,
	Poison,
	Bleeding,
};

namespace DarkGameplayTags
{
	DARKSCRIPT_API FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);
	DARKSCRIPT_API FGameplayTag FindResistanceTagByEnum(const EGameplayTagResistances Resistance);

	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_Type_Physic_Melee);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_Type_Physic_Ranged);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_Type_Magical);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_Type_Healing);
	
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Damage);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_ArmorPenetration);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_FleshMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_PenetrationMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_IceMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_FireMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_LightningMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_HolyMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_PoisonMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_BleedingMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_HealingMultiplier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Causer_PropertyType_Multiplier_SpeedMultiplier);
	

	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_HealthMax);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_HealthRegenRate);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resource_StaminaMax);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resource_StaminaRegenRate);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resource_ManaMax);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resource_ManaRegenRate);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resource_FocusMax);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resource_FocusRegenRate);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Armor);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Perk_Vitality);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Perk_Strength);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Perk_Accuracy);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Perk_Intelligence);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Perk_Mentality);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Armor);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Ice);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Fire);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Lightning);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Holy);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Poison);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Resistance_Bleeding);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Physic);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Ranged);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Magic);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Physic_CriticalChance);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Physic_CriticalPower);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Magic_CriticalChance);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Damage_Magic_CriticalPower);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Heal);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Heal_CriticalChance);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Character_PropertyType_Heal_CriticalPower);

	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Flesh_Melee);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Flesh_Ranged);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Penetration_Melee);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Penetration_Ranged);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Ice);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Fire);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Lightning);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Holy);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Poison);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Ability_Damage_Type_Bleeding);
	
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Duration);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Modifier);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);
	
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modifier_Resistance);
	DARKSCRIPT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Modifier_MultiplierType);
}
